name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier:check
      - name: Build
        run: |
          npm run build
          npm pack
          npm run self-test
      - name: Jest
        run: npm test
        env:
          CI: true
